/* 06102022 */
*************************************************************
************************************************************;
libname file "<FILE LOCATION>";
*************************************************************
************************************************************;

data screener;
	set file.nsch_2021_screener;
	label
C_FWS="Child Weight"
C_CSHCN="Special Health Care Needs Status of Child"
C_K2Q23="Child Treatment for Chronic Emotion Develop Behave"
C_K2Q22="Child Needs Treatment for Emotion Develop Behave"
C_K2Q21="Child Special Therapy for Health Condition for 12 Months"
C_K2Q20="Child Special Therapy for Health Condition"
C_K2Q19="Child Special Therapy"
C_K2Q18="Child Limited Ability from Health Condition for 12 Months"
C_K2Q17="Child Limited Ability from Health Condition"
C_K2Q16="Child Limited Ability"
C_K2Q15="Child Medical Care Currently for 12 Months"
C_K2Q14="Child Medical Care Used or Needed for Health Condition"
C_K2Q13="Child Needs or Uses More Medical Care than Others"
C_K2Q12="Child Medication Currently for 12 Months"
C_K2Q11="Child Medication Used or Needed for Health Condition"
C_K2Q10="Child Needs or Uses Medication Currently"
C_RACE_R_IF="Imputation Flag for C_RACE_R"
C_HISPANIC_R_IF="Imputation Flag for C_HISPANIC_R"
C_SEX_IF="Imputation Flag for C_SEX"
C_ENGLISH="Child Speak English"
C_SEX="Child Sex"
C_HISPANIC_R="Hispanic Origin of Child, Recode"
RACEAIAN="Race of Child, Recode, AIAN included. Reported for AK, AZ, NM, MT, ND, OK, SD."
RACEASIA="Race of Child, Recode, Asian included. Reported for CA, HI, MA, MD, MN, NJ, NV, NY, VA, WA."
RACER="Race of Child, Recode"
C_RACE_R="Race of Child, Detailed"
C_AGE_YEARS="Child Age - Years"
YEAR="Survey Year"
LINENUM="Child Line Number"
MPC_YN="Metropolitan Principal City Status"
METRO_YN="Metropolitan Statistical Area Status"
CBSAFP_YN="Core Based Statistical Area Status"
HHLANGUAGE="Primary Household Language"
TOTKIDS_R="Number of Children in Household"
FIPSST="State FIPS Code"
FWH="Household Weight"
STRATUM="Sampling Stratum"
HHIDS="Unique Household ID (Screener)"
TENURE="The Conditions under Which Land or Buildings Are Held or Occupied"
TENURE_IF="Imputation Flag for C_SEX"
;
run;

PROC FORMAT;
VALUE CBSAFP_YN_LAB 1='Located within a CBSA'
2='Located outside a CBSA'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_AGE_YEARS_LAB .M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_CSHCN_LAB 1='Special Health Care Needs'
2='No Special Health Care Needs'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_ENGLISH_LAB 1='Very well'
2='Well'
3='Not well'
4='Not at all'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_FWS_LAB .M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_HISPANIC_R_LAB 1='Hispanic or Latino Origin'
2='Not Hispanic or Latino Origin'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_HISPANIC_R_IF_LAB 1='Imputed'
0='Not imputed'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_K2Q10_LAB 1='Yes'
2='No'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_K2Q11_LAB 1='Yes'
2='No'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_K2Q12_LAB 1='Yes'
2='No'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_K2Q13_LAB 1='Yes'
2='No'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_K2Q14_LAB 1='Yes'
2='No'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_K2Q15_LAB 1='Yes'
2='No'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_K2Q16_LAB 1='Yes'
2='No'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_K2Q17_LAB 1='Yes'
2='No'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_K2Q18_LAB 1='Yes'
2='No'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_K2Q19_LAB 1='Yes'
2='No'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_K2Q20_LAB 1='Yes'
2='No'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_K2Q21_LAB 1='Yes'
2='No'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_K2Q22_LAB 1='Yes'
2='No'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_K2Q23_LAB 1='Yes'
2='No'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_RACE_R_LAB 1='White alone'
2='Black or African American alone'
3='American Indian or Alaska Native alone'
4='Asian alone'
5='Native Hawaiian and Other Pacific Islander alone'
7='Two or More Races'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_RACE_R_IF_LAB 1='Imputed'
0='Not imputed'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_SEX_LAB 1='Male'
2='Female'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE C_SEX_IF_LAB 1='Imputed'
0='Not imputed'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE FWH_LAB .M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE HHIDS_LAB .M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE HHLANGUAGE_LAB 1='English'
2='Spanish'
3='Other'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE LINENUM_LAB .M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE METRO_YN_LAB 1='Metropolitan Statistical Area'
2='Not Metropolitan Statistical Area'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE MPC_YN_LAB 1='Metropolitan Principal City'
2='Not Metropolitan Principal City'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE RACEAIAN_LAB 1='White alone'
2='Black or African American alone'
3='American Indian or Alaska Native alone'
4='Other'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE RACEASIA_LAB 1='White alone'
2='Black or African American alone'
3='Asian alone'
4='Other'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE RACER_LAB 1='White alone'
2='Black or African American alone'
3='Other'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE TENURE_LAB 1='Owned by you or someone in this household with a mortgage or loan? Include home equity loans'
2='Owned by you or someone in this household free and clear (without a mortgage or loan)?'
3='Rented?'
4='Occupied without payment of rent?'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE TENURE_IF_LAB 1='Imputed'
0='Not imputed'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE TOTKIDS_R_LAB 1='1'
2='2'
3='3'
4='4+'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
VALUE YEAR_LAB .M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';

VALUE $FIPSST_LAB
01='Alabama'
02='Alaska'
04='Arizona'
05='Arkansas'
06='California'
08='Colorado'
09='Connecticut'
10='Delaware'
11='District of Columbia'
12='Florida'
13='Georgia'
15='Hawaii'
16='Idaho'
17='Illinois'
18='Indiana'
19='Iowa'
20='Kansas'
21='Kentucky'
22='Louisiana'
23='Maine'
24='Maryland'
25='Massachusetts'
26='Michigan'
27='Minnesota'
28='Mississippi'
29='Missouri'
30='Montana'
31='Nebraska'
32='Nevada'
33='New Hampshire'
34='New Jersey'
35='New Mexico'
36='New York'
37='North Carolina'
38='North Dakota'
39='Ohio'
40='Oklahoma'
41='Oregon'
42='Pennsylvania'
44='Rhode Island'
45='South Carolina'
46='South Dakota'
47='Tennessee'
48='Texas'
49='Utah'
50='Vermont'
51='Virginia'
53='Washington'
54='West Virginia'
55='Wisconsin'
56='Wyoming'
.M='No valid response'
.N='Not in universe'
.L='Logical skip'
.D='Suppressed for confidentiality';
run;
